const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  RESTAURANT_OWNER: "RESTAURANT_OWNER",
  OUTLET_MANAGER: "OUTLET_MANAGER",
  STAFF: "STAFF",
};

const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  BLOCKED: "BLOCKED",
};

const ORDER_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  PREPARING: "PREPARING",
  READY: "READY",
  PICKED_UP: "PICKED_UP",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

const SUBSCRIPTION_PLANS = {
  FREE: "FREE",
  STARTER: "STARTER",
  PRO: "PRO",
  ENTERPRISE: "ENTERPRISE",
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  ORDER_STATUS,
  PAYMENT_STATUS,
  SUBSCRIPTION_PLANS,
};
